### ISSUE TITLE
iscsi infra question

### ISSUE THREAD

**Issue by nlopez** [nicolerenee/k8s-state#1]
Hi @nicolerenee ! A friend of mine linked to your repo and I was amazed by the similarities to [my home k8s setup](https://github.com/nlopez/k8s_home).

I'm running on 3x Intel NUCs with kuberouter rather than metallb. I like how you've got Plex + Tautulli in the same pod, which makes a lot of sense and is an improvement I'm going to adopt. 

I'm curious what you're using to provide the iscsi targets in your k8s manifests. I'm running FreeNAS on two NAS'es at home, but haven't used their iSCSI capabilities yet, so right now my persistent storage for k8s is local to the k8s nodes (in the case of config and non-media data) or via NFS mounts.

For media I'll probably continue using NFS, since it needs to be mounted by multiple services. But I like the idea of using iSCSI in place of my k8s node local storage.

**Comment by nicolerenee** [comment]
Yeah, so I have a synology right now and I'm just using the built in iSCSI that it offers. I found with plex in particular running the config from a NFS share was painful vs localdisk or iscsi. So I switched it and then made the same move for everything else. I find that it works extremely well, and helps enforce only 1 writer. I've had a few times where a kubelet went haywire and the pods on it weren't down and kubernetes started rescheduling (mostly due to errors in my config) and it would have led to a lose of data had it been nfs. 

In all honesty I'm likely going to be moving Tautulli into a separate pod. It's very annoying to require plex to go offline just so I can update Tautulli. The only reason this hasn't happened yet is I just haven't gotten around to building a nfs share for the plex logs so that I can mount them read only to Tautulli.

**Comment by nlopez** [comment]
Oh good point on updating Tautulli independently of Plex. I guess I'll keep mine separate and move logs to NFS, too.

I'm interested to see how your setup evolves. This inspired a [major refactor](https://github.com/nlopez/k8s_home/compare/before-iscsi-networkpolicy...after-iscsi-networkpolicy?diff=combined&name=after-iscsi-networkpolicy) of my own k8s configs, and now I have iSCSI for everything, network policies with ingress default deny, better namespace organization, and I'm beginning to play with pod anti-affinity for keeping other bandwidth-intensive apps away from Plex.

[weaveworks/flux](https://github.com/weaveworks/flux) looks great for getting CI on this and I'm going to try that next. 😁Cheers!

**Comment by nicolerenee** [comment]
One thing I found was when using a hostname for the iscsi target (https://github.com/nlopez/k8s_home/compare/before-iscsi-networkpolicy...after-iscsi-networkpolicy?diff=combined&name=after-iscsi-networkpolicy#diff-ff64abe2ad752df20da470f131af39c7R17) caused the volume to fail to mount. In my case iscsi-initiator on the host converted the hostname to the IP so when k8s would go check for the connection it couldn't find it and would try again, which would fail because it was already mounted.

**Comment by nlopez** [comment]
Thanks for the heads up on the iscsi initiator DNS issue. I haven't ran into it yet but I'll keep it in mind when I go to troubleshoot things.

Re: your use of the [i915 resources here for Plex](https://github.com/nicolerenee/k8s-state/blob/334928b/media/plex/deployment.yaml#L41-L43), do you have this working with Plex's hardware transcoding?

I have my (also i915 driver) GPU working with Plex [like this, via a CharDevice host volume](https://github.com/nlopez/k8s_home/blob/331b52c/media/pms/deployment.yaml#L19-L26), but I'd much rather get this done with a device plugin if possible. [Is this what you used?](https://github.com/intel/intel-device-plugins-for-kubernetes/blob/master/cmd/gpu_plugin/README.md) If so, I'm curious whether you're running it just as a process on the k8s node, or have it [deployed to the cluster as a DS like their other examples](https://github.com/intel/intel-device-plugins-for-kubernetes/blob/master/cmd/fpga_plugin/README.md#deploy-fpga-device-plugin-as-daemonset) (not sure why they don't have this for the GPU plugin.)

**Comment by nicolerenee** [comment]
I do have it working with Plex's hardware transcoding. I'm using the gpu_plugin that you linked to. I plan to eventually make it a daemon set, but right now it is running on the host system.

**Comment by tubit** [comment]
Hi there,

I just stumbled across this repo and your discussion. I also run a k8s at home and migrated everything from iscsi to glusterfs w/ heketi. Maybe it’s worth a look for you both.

The main reason for me was that I do not have a dedicated NAS at home - so on of my k8s hosts (the master) has all disks for media files and shares them via nfs. Iscsi worked for config volumes etc (for Plex) but as all nodes had some GB left on their SSD I just created a glusterfs cluster and migrated away from iscsi. Much better handling thanks to heketi.

Cheers
Dennis
